#!/bin/sh

configFile="/boot/firmware/config.txt";
found=;

while IFS= read -r line || [ -n "$line" ]; do
    if [ "$line" = "disable_overscan=1" ]; then
        found="1";
    fi;
done < $configFile;

if [ ! $found ]; then
    printf "
# Remove black borders
disable_overscan=1

# Overclock
over_voltage=6
arm_freq=2147
gpu_freq=750
" >> $configFile;
fi;
